server:
  port: 9090

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:bankingmanagement
  jpa:
    show-sql: true

# To set logs level as per your need.
logging:
  level:
    com:
      bankingmanagement: debug
  file:
    name: spring_app_log_file.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: info,health,metrics,loggers,beans,mappings,threaddump,env,caches
  endpoint:
    health:
      show-details: always
